# ==============================================================================
# Quartus Prime Synopsys Design Constraint File
# Generated by OpenGateware - Gateman CLI v0.1.0
# ==============================================================================
# Analogue Pocket SDC settings
# Users are recommended to modify this file to match users logic.
# Put your clock groups in here as well as any net assignments.
# ==============================================================================

# ==============================================================================
# Time Information
# ==============================================================================

# ==============================================================================
# Create Clock
# ==============================================================================

# ==============================================================================
# Create Generated Clock
# ==============================================================================

# ==============================================================================
# Set Clock Latency
# ==============================================================================

# ==============================================================================
# Set Clock Uncertainty
# ==============================================================================

# ==============================================================================
# Set Input Delay
# ==============================================================================
set_input_delay -clock { ic|core_pll|core_pll_inst|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk } -max 6.4 [get_ports dram_dq[*]]
set_input_delay -clock { ic|core_pll|core_pll_inst|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk } -min 3.1 [get_ports dram_dq[*]]

# ==============================================================================
# Set Output Delay
# ==============================================================================
# tDH, hold time, spec is 0.8ns
# tDS, setup time, spec is 1.5ns
set_output_delay -clock { ic|core_pll|core_pll_inst|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk } -min -0.8 [get_ports {dram_a[*] dram_ba[*] dram_cke dram_dqm[*] dram_dq[*] dram_ras_n dram_cas_n dram_we_n}]
set_output_delay -clock { ic|core_pll|core_pll_inst|altera_pll_i|general[0].gpll~PLL_OUTPUT_COUNTER|divclk } -max 1.5 [get_ports {dram_a[*] dram_ba[*] dram_cke dram_dqm[*] dram_dq[*] dram_ras_n dram_cas_n dram_we_n}]

# ==============================================================================
# Set Clock Groups
# ==============================================================================

# ==============================================================================
# Set False Path
# ==============================================================================

# ==============================================================================
# Set Multicycle Path
# ==============================================================================
set_multicycle_path -from {ic|m72:m72|mcu:mcu|mc8051_core:mc8051|*}  -setup 2
set_multicycle_path -from {ic|m72:m72|mcu:mcu|mc8051_core:mc8051|*}  -hold 1
set_multicycle_path -from {ic|m72:m72|mcu:mcu|dpramv:prom|altsyncram:ram_rtl_0|*} -to {ic|m72:m72|mcu:mcu|mc8051_core:mc8051|mc8051_control:i_mc8051_control|*} -setup 2
set_multicycle_path -from {ic|m72:m72|mcu:mcu|dpramv:prom|altsyncram:ram_rtl_0|*} -to {ic|m72:m72|mcu:mcu|mc8051_core:mc8051|mc8051_control:i_mc8051_control|*} -hold 1
set_multicycle_path -from {ic|m72:m72|mcu:mcu|dpramv:prom|altsyncram:ram_rtl_0|*} -to {ic|m72:m72|mcu:mcu|prom_addr[*]} -setup 2
set_multicycle_path -from {ic|m72:m72|mcu:mcu|dpramv:prom|altsyncram:ram_rtl_0|*} -to {ic|m72:m72|mcu:mcu|prom_addr[*]} -hold 1

# ==============================================================================
# Set Maximum Delay
# ==============================================================================

# ==============================================================================
# Set Minimum Delay
# ==============================================================================

# ==============================================================================
# Set Input Transition
# ==============================================================================

